### ISSUE TITLE
Issue trying to update bower.json file

### ISSUE THREAD

**Issue by grafikkaos** [se-panfilov/bower-check-updates#12]
I am having an issue trying to update my bower.json file.

When I run bcu -u, I get the following error:

Unhandled rejection Error: TypeError: Cannot read property 'dist-tags.latest' of undefined
    at C:\Users\Emmanuel\AppData\Roaming\npm\node_modules\bower-check-updates\lib\versionmanager.js:356:31
    at tryCatcher (C:\Users\Emmanuel\AppData\Roaming\npm\node_modules\bower-check-updates\node_modules\bluebird\js\main\util.js:26:23)
    at MappingPromiseArray._promiseFulfilled (C:\Users\Emmanuel\AppData\Roaming\npm\node_modules\bower-check-updates\node_modules\bluebird\js\main\map.js:56:38)
    at MappingPromiseArray.init [as _init$](C:UsersEmmanuelAppDataRoamingnpmnode_modulesbower-check-updatesnode_modulesbluebirdjsmainpromise_array.js:92:18)
    at MappingPromiseArray.init (C:\Users\Emmanuel\AppData\Roaming\npm\node_modules\bower-check-updates\node_modules\bluebird\js\main\map.js:29:23)
    at Async._drainQueue (C:\Users\Emmanuel\AppData\Roaming\npm\node_modules\bower-check-updates\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (C:\Users\Emmanuel\AppData\Roaming\npm\node_modules\bower-check-updates\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate](C:UsersEmmanuelAppDataRoamingnpmnode_modulesbower-check-updatesnode_modulesbluebirdjsmainasync.js:15:14)
    at processImmediate [as _immediateCallback](timers.js:367:17)

Is there something I can do to fix this?

Thanks

**Comment by se-panfilov** [comment]
@grafikkaos Hi. Can you attach your `bower.json` please?

**Comment by grafikkaos** [comment]
Sorry for the delay but this is my bower,json file..

```
{
  "name": "laravel-dev5",
  "version": "0.0.0",
  "authors": [
    "test user <test@user.com>"
  ],
  "license": "MIT",
  "private": true,
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "resources/assets/bower_components/",
    "test",
    "tests"
  ],
  "dependencies": {
    "alloy-editor": "https://github.com/liferay/alloy-editor.git#~0.2.7",
    "angular": "~1.4.3",
    "angular-moment": "~0.10.2",
    "angular-sanitize": "~1.4.3",
    "angular-ui-bootstrap": "~0.13.2",
    "animate-sass": "~0.6.2",
    "awesome-bootstrap-checkbox": "~0.2.3",
    "blockUI": "*",
    "blueimp-file-upload": "~9.10.6",
    "bootstrap-daterangepicker": "~2.0.6",
    "bootstrap-sass-official": "~3.3.3",
    "bootstrap-social": "~4.9.1",
    "bootstrap3-dialog": "~1.34.4",
    "jquery-legacy": "jquery#1",
    "jquery-migrate": "~1.2.1",
    "jquery-modern": "jquery#~2.1.3",
    "jquery-mousewheel": "~3.1.13",
    "jQuery-QueryBuilder": "https://github.com/mistic100/jQuery-QueryBuilder.git#~2.2.0",
    "jquery-slugify": "~1.2.1",
    "jquery-ui": "~1.11.3",
    "jquery.steps": "~1.1.0",
    "jrac": "*"
  },
  "resolutions": {
    "sifter": "0.4.x",
    "font-awesome": "~4.4.0",
    "angular": "~1.4.3",
    "jquery": ">=1.10",
    "moment": "~2.9.0",
    "selectize": "~0.12.1"
  }
}
```

**Comment by se-panfilov** [comment]
Library has depreciated, please use [npm-check-updates](https://github.com/tjunnone/npm-check-updates) instead :

```
//in bower mode
$ ncu -m bower
```
